// flags.js
module.exports = {
    'Australia': '/flags/australia.webp',
    'China': '/flags/china.webp',
    'Japón': '/flags/japan.webp',
    'Bahrein': '/flags/bahrain.webp',
    'Arabia': '/flags/saudi_arabia.webp',
    'Miami': '/flags/usa.webp',
    'Emilia Romagna': '/flags/italy.webp',
    'Mónaco': '/flags/monaco.webp',
    'Canadá': '/flags/canada.webp',
    'España': '/flags/spain.webp',
    'Austria': '/flags/austria.webp',
    'Gran Bretaña': '/flags/great-britain.webp', 
    'Hungría': '/flags/hungary.webp',
    'Bélgica': '/flags/belgium.webp',
    'Países Bajos': '/flags/netherlands.webp', 
    'Italia': '/flags/italy.webp',
    'Azerbaiyán': '/flags/azerbaijan.webp',
    'Singapur': '/flags/singapore.webp',
    'Estados Unidos': '/flags/usa.webp',
    'Ciudad de México': '/flags/mexico.webp', 
    'Sao Paulo': '/flags/brazil.webp',
    'Las Vegas': '/flags/usa.webp',
    'Qatar': '/flags/qatar.webp',
    'Abu Dhabi': '/flags/uae.webp',
    'Sakhir': '/flags/bahrain.webp',
    'Indonesia': '/flags/indonesia.webp',
    'Tailandia': '/flags/thailand.webp',
    'Malasia': '/flags/malaysia.webp',
    'Portugal': '/flags/portugal.webp',
    'Francia': '/flags/france.webp',
    'Cataluña': '/flags/spain.webp',
    'Alemania': '/flags/germany.webp',
    'Argentina': '/flags/argentina.webp',
    'Americas': '/flags/usa.webp',
    'Aragón': '/flags/spain.webp',
    'República Checa': '/flags/czech-republic.webp',
    'San Marino': '/flags/italy.webp',
    'Valencia': '/flags/spain.webp',
    'St. Petersburg:': '/flags/usa.webp',
    'The Thermal Club': '/flags/usa.webp',
    'Long Beach': '/flags/usa.webp',
    'Barber Motorsports': '/flags/usa.webp',
    'Indianápolis (Road Course)': '/flags/usa.webp',
    '500 Millas de Indianápolis': '/flags/usa.webp',
    'Detroit': '/flags/usa.webp',
    'Madison': '/flags/usa.webp',
    'Road Americas': '/flags/usa.webp',
    'Mid Ohio': '/flags/usa.webp',
    'Iowa 1': '/flags/usa.webp',
    'Iowa 2': '/flags/usa.webp',
    'Toronto': '/flags/canada.webp',
    'Laguna Seca': '/flags/usa.webp',
    'Portland': '/flags/usa.webp',
    'Milwaukee': '/flags/usa.webp',
    'Nashville': '/flags/usa.webp',
};