name: Update Standings

on:
  schedule:
    # Execute every half hour on Saturdays, Sundays, and Mondays
    - cron: '*/30 * * * 6,0,1'
  workflow_dispatch:

jobs:
  update-standings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Configure SUID sandbox
        run: |
          sudo chown root:root /home/runner/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome_sandbox
          sudo chmod 4755 /home/runner/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome_sandbox
          echo "CHROME_DEVEL_SANDBOX=/home/runner/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome_sandbox" >> $GITHUB_ENV
      - name: Update standings
        run: node main.js standings
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}